[package]
name = "xtest-data"
version = "0.0.2"
description = "Use test data in distributed integration tests without packaging it"
license = "MIT OR Apache-2.0 OR Zlib"
edition = "2018"
repository = "https://github.com/HeroicKatora/xtest-data"
exclude = ["tests/data.zip"]

[dependencies.serde_json]
version = "1"
default-features = false
features = ["alloc"]
[dependencies.slotmap]
version = "1"
default-features = false
[dependencies.url]
version = "2"
default-features = false
[dependencies.which]
version = "4.2"

[workspace]
members = [".", "xtask"]
exclude = ["target/**"]
