[package]
name = "xtest-data"
version = "0.0.1"
edition = "2018"
publish = false
repository = "https://github.com/HeroicKatora/xtest-data"
exclude = ["tests/data.zip"]

[dependencies]
hex = "0.4.3"
serde_json = "1"
slotmap = "1"
url = "2"
which = "4.2"
