[package]
name = "xtest-data"
version = "0.0.1"
edition = "2018"
publish = false
repository = "https://github.com/HeroicKatora/xtest-data"
exclude = ["tests/data.zip"]

[dependencies.hex]
version = "0.4.3"
default-features = false
features = ["alloc"]
[dependencies.serde_json]
version = "1"
default-features = false
features = ["alloc"]
[dependencies.slotmap]
version = "1"
default-features = false
[dependencies.url]
version = "2"
default-features = false
[dependencies.which]
version = "4.2"
