[package]
name = "xtest-data"
version = "0.0.3"
description = "Use test data in distributed integration tests without packaging it"
license = "MIT OR Apache-2.0 OR Zlib"
edition = "2018"
repository = "https://github.com/HeroicKatora/xtest-data"
exclude = ["tests/data.zip"]

[dependencies.tinyjson]
version = "2"
[dependencies.fslock]
version = "0.1.8"
features = ["multilock"]
[dependencies.which]
version = "4.2"

[workspace]
members = [".", "xtask"]
exclude = ["target/**"]
