[package]
name = "xtask"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
clap = "3"
serde = { version = "1", features = ["derive"] }
tempdir = "0.3.7"
tinytemplate = "1"
toml = "0.5"
ureq = "2.5"
