name: Rust CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install chosen toolchain
      uses: mkroening/rust-toolchain-toml@main
    - uses: Swatinem/rust-cache@v2
      name: Cache the Rust build
      with:
        save-if: ${{ github.ref == 'refs/heads/master' }}
    - name: test
      run: cargo run --bin cargo-xtest-data --features=bin-xtask -- xtest-data test
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install chosen toolchain
      uses: mkroening/rust-toolchain-toml@main
      with:
        toolchain-file: ".github/rust-toolchain.toml"
    - uses: Swatinem/rust-cache@v2
      name: Cache the Rust build
      with:
        save-if: ${{ github.ref == 'refs/heads/master' }}
    - name: Run rustfmt check
      run: cargo fmt -- --check
