name: Rust CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install chosen toolchain
      uses: mkroening/rust-toolchain-toml@v1.2.0
    - name: test
      run: cargo run --bin xtask --features=bin-xtask -- test
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install chosen toolchain
      uses: mkroening/rust-toolchain-toml@v1.2.0
      with:
        toolchain-file: ".github/rust-toolchain.toml"
    - name: Run rustfmt check
      run: cargo fmt -- --check
