name: Releases
on:
  push:
    tags:
    - 'v*'
jobs:
  test-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust stable
      uses: mkroening/rust-toolchain-toml@main
    - uses: Swatinem/rust-cache@v2
      name: Cache the Rust build
      with:
        shared-key: generic-jobs
        save-if: false
    - name: Create test data
      run: >
        mv "$(cargo run --bin cargo-xtest-data --features=bin-xtask -- xtest-data pack)" "xtest-data.tar.gz"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "xtest-data.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
